### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.Interceptor"  启动崩溃.

### ISSUE THREAD

**Issue by yanweinet** [RxReader/tencent_kit#52]
I/AttaReporter(31145): init
I/openSDK_LOG.SystemUtils(31145): isQQInstalled true
I/AttaReporter(31145): attaReportAtSubThread
E/AndroidRuntime(31145): FATAL EXCEPTION: main
E/AndroidRuntime(31145): Process: io.github.v7lin.tencent_kit_example, PID: 31145
E/AndroidRuntime(31145): java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/Interceptor;
E/AndroidRuntime(31145): 	at com.tencent.open.a.a.a(ProGuard:68)
E/AndroidRuntime(31145): 	at com.tencent.tauth.Tencent.createInstance(ProGuard:113)
E/AndroidRuntime(31145): 	at com.tencent.tauth.Tencent.createInstance(ProGuard:75)
E/AndroidRuntime(31145): 	at io.github.v7lin.tencent_kit.TencentKitPlugin.onMethodCall(TencentKitPlugin.java:181)
E/AndroidRuntime(31145): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(31145): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(31145): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime(31145): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(31145): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(31145): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime(31145): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(31145): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31145): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(31145): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(31145): Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.Interceptor" on path: DexPathList[[zip file "/data/app/io.github.v7lin.tencent_kit_example-AmurMVlb-z5GtydQJRuFxQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.github.v7lin

-------------------------------------------------
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web

**Comment by snkkka163** [comment]
一样的问题！
